language: python
name: "python unit tests & code style"
python:
  - "3.6"
  - "3.8"
cache: pip
env:
  - TSPLIB_ROOT="../tsplib95/archives/problems/tsp" OPLIB_ROOT="../OPLib/"
before_install:
  - git clone https://github.com/bcamath-ds/OPLib.git ../OPLib
  - git clone https://github.com/rhgrant10/tsplib95.git ../tsplib95
install:
  # install conda
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  # create conda env and activate
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
  - conda activate test-environment
  # install graph tool
  - conda install -c conda-forge graph-tool
  # install our package
  - pip install .
  - pip install -r requirements.txt
script:
  # Check black formatting would not make any chages
  - black --check */
  # pylint provides stricter linting
  - pylint --rcfile .pylintrc setup.py tspwplib tests/*
  # type hinting
  - mypy --config-file .mypy.ini tspwplib
  # Run unit tests
  - python -m pytest
