language: python
name: "python unit tests & code style"
python:
  - "3.6"
  - "3.8"
cache: pip
env:
  - TSPLIB_ROOT="$(pwd)/tsblib95/archives/problems/tsp"
  - OPLIB_ROOT="$(pwd)/OPLib/"
before_install:
  - git clone https://github.com/bcamath-ds/OPLib.git
  - git clone git://github.com/rhgrant10/tsplib95
install:
  - pip install .
  - pip install -r requirements.txt
script:
  # Check black formatting would not make any chages
  - black --check */
  # pylint provides stricter linting
  - pylint --rcfile .pylintrc setup.py tspwp tests/*
  # type hinting
  - mypy --config-file .mypy.ini tspwp
  # Run unit tests
  - python -m pytest
